lib/basic_ads_web/router.ex
defmodule BasicAdsWeb.Router do
  use BasicAdsWeb, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", BasicAdsWeb do
    pipe_through :browser
    get "/ads/cat/:id", AdvertisementController, :index_category
    get "/ads/sub/:id", AdvertisementController, :index_subcategory
    resources "/ads", AdvertisementController, only: [:index, :new, :create, :show]
    get "/", CategoryController, :index
  end

  # Other scopes may use custom stacks.
  # scope "/api", BasicAdsWeb do
  #   pipe_through :api
  # end

  # Enables LiveDashboard only for development
  #
  # If you want to use the LiveDashboard in production, you should put
  # it behind authentication and allow only admins to access it.
  # If your application does not have an admins-only section yet,
  # you can use Plug.BasicAuth to set up some basic authentication
  # as long as you are also using SSL (which you should anyway).
  if Mix.env() in [:dev, :test] do
    import Phoenix.LiveDashboard.Router

    scope "/" do
      pipe_through :browser
      live_dashboard "/dashboard", metrics: BasicAdsWeb.Telemetry
    end
  end
end

lib/basic_ads_web/views/layout_view.ex
defmodule BasicAdsWeb.LayoutView do
  use BasicAdsWeb, :view
end

lib/basic_ads_web/templates/layout/app.html.eex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8"/>
    <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <title><%= @view_module.title(@view_template, assigns) %></title>
    <link rel="stylesheet" href="<%= Routes.static_path(@conn, "/css/app.css") %>"/>
    <script defer type="text/javascript" src="<%= Routes.static_path(@conn, "/js/app.js") %>"></script>
  </head>
  <body>
    <header>
      <nav class="demo">
        <a href="/" class="brand">
          <span>Anuncios Clasificados</span>
        </a>
        <input id="bmenub" type="checkbox" class="show">
        <label for="bmenub" class="burger pseudo button">&#9776;</label>
        <div class="menu">
          <%= link "Nuevo Anuncio", to: Routes.advertisement_path(@conn, :new), class: "button" %>
        </div>
      </nav>
    </header>
    <main role="main">
      <%= if assigns[:show_search] do %>
        <div class="grid grid-center search-section">
          <div class="col col-6">
            <%= render BasicAdsWeb.AdvertisementView, "search.html", conn: @conn, main_page: assigns[:main_page] %>
          </div>
        </div>
      <% end %>
      <%= @inner_content %>
    </main>
  </body>
</html>